import = ["~/.config/alacritty/theme/kanagawa.toml"]

[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"

[window.padding]
x = 7
y = 0

[window]
decorations = "none"

[shell]
program = "tmux"

[env]
TERM = "xterm-256color"
